SELECT*FROM [LMS_BOOK_DETAILS]
SELECT*FROM [LMS_MEMBERS]
SELECT*FROM [LMS_BOOK_ISSUE]
SELECT*FROM [LMS_FINE_DETAILS]
SELECT*FROM [LMS_SUPPLIERS_DETAILS]

--Q1
SELECT MEMBER_ID,MEMBER_NAME,city,MEMBERSHIP_STATUS from [LMS_MEMBERS] where MEMBERSHIP_STATUS='Permanent';

--Q2
SELECT BOOK_CODE,PUBLICATION,PRICE,SUPPLIER_ID from [LMS_BOOK_DETAILS] where CATEGORY='java';
--Q3
SELECT MEMBER_NAME,BOOK_CODE from [LMS_MEMBERS],[LMS_BOOK_ISSUE] where BOOK_CODE='BL000002'

--Q4
SELECT BOOK_CODE,BOOK_TITLE,AUTHOR from [LMS_BOOK_DETAILS] where AUTHOR like 'p%'
--Q5
SELECT COUNT(CATEGORY)as NO_OF_BOOK from [LMS_BOOK_DETAILS] where CATEGORY='JAVA'
--Q6
SELECT CATEGORY,COUNT(CATEGORY)as NO_OF_BOOKS from [LMS_BOOK_DETAILS] group by CATEGORY
--Q7
SELECT count(book_code) as NOOFBOOKS from [LMS_BOOK_DETAILS] where PUBLICATION='Prentice Hall'
--Q8
SELECT b1.BOOK_CODE,BOOK_TITLE,b2.DATE_ISSUE from LMS_BOOK_DETAILS b1 join LMS_BOOK_ISSUE b2 on b1.BOOK_CODE=b2.BOOK_CODE where b2.BOOK_CODE in
(select b1.BOOK_CODE from LMS_BOOK_DETAILS)
--Q9
SELECT MEMBER_ID,MEMBER_NAME,DATE_REGISTER,DATE_EXPIRE FROM LMS_MEMBERS where DATE_EXPIRE<'2013-03-01'
--Q10
select MEMBER_ID,MEMBER_NAME,DATE_REGISTER,MEMBERSHIP_STATUS from LMS_MEMBERS where DATE_REGISTER<'2012-05-13' and MEMBERSHIP_STATUS='Temporary';
--Q11
select MEMBER_ID,MEMBER_NAME as Name,CITY from LMS_MEMBERS where CITY='CHENNAI' or CITY='DELHI';
--Q12
select BOOK_TITLE +'_is_written_by'+AUTHOR as BOOK_WRITTEN_BY from LMS_BOOK_DETAILS


SELECT*FROM LMS_MEMBERS
SELECT*FROM [LMS_BOOK_ISSUE]
SELECT*FROM LMS_SUPPLIERS_DETAILS
SELECT*FROM LMS_FINE_DETAILS
SELECT*FROM LMS_MEMBERS
SELECT*FROM LMS_BOOK_DETAILS


select distinct BOOK_TITLE,MEMBER_ID from LMS_BOOK_DETAILS  join [LMS_BOOK_ISSUE] on LMS_BOOK_DETAILS.BOOK_CODE=[LMS_BOOK_ISSUE].BOOK_CODE
--Q1
select lp.BOOK_TITLE,pl.SUPPLIER_NAME from LMS_BOOK_DETAILS lp join LMS_SUPPLIERS_DETAILS pl on lp.SUPPLIER_ID=pl.SUPPLIER_ID
--Q2
select lp.MEMBER_NAME,pl.BOOK_CODE FROM LMS_MEMBERS lp join [LMS_BOOK_ISSUE] pl on lp.MEMBER_ID=pl.MEMBER_ID
--Q3
select lp.BOOK_TITLE,DATE_ISSUE  from [LMS_BOOK_DETAILS] lp join [LMS_BOOK_ISSUE] pl on lp.BOOK_CODE=pl.BOOK_CODE
--Q4
select lp.member_id,pl.FINE_RANGE from  LMS_MEMBERS lp join [LMS_BOOK_ISSUE] pl on lp.MEMBER_ID=pl.MEMBER_ID
 
--Q5
select lp.member_name,pl.DATE_RETURN,pl.DATE_RETURNED from LMS_MEMBERS lp join LMS_BOOK_ISSUE pl on lp.MEMBER_ID=pl.MEMBER_ID
--Q6
select lp.BOOK_TITLE,pl.MEMBER_NAME from LMS_BOOK_DETAILS lp join LMS_BOOK_ISSUE kl on lp.BOOK_CODE=kl.BOOK_CODE join LMS_MEMBERS pl on
pl.MEMBER_ID=kl.MEMBER_ID
--Q7
select lp.book_title,m.member_name,s.SUPPLIER_NAME from LMS_BOOK_DETAILS lp join LMS_BOOK_ISSUE pl on lp.BOOK_CODE=pl.BOOK_CODE join
LMS_MEMBERS m on m.MEMBER_ID=pl.MEMBER_ID join LMS_SUPPLIERS_DETAILS s on s.SUPPLIER_ID=lp.SUPPLIER_ID
--Q8
select lp.BOOK_TITLE,f.FINE_AMOUNT from LMS_BOOK_DETAILS lp join LMS_BOOK_ISSUE pl on lp.BOOK_CODE=pl.BOOK_CODE join LMS_FINE_DETAILS f on
f.FINE_RANGE=pl.FINE_RANGE
